ublue-os/hwe

- Containerfile
This PR's changes won't affect the image outcome. It's just my take on improving Containerfile readability.
> Containerfile: improve readability

- .github/workflows/build.yml
- README.md
* Add documentation improvements from my brief fork
* Postfix public image names with -nvidia
* Add install commands for both editions.
* Add a dispatch trigger to facilitate triggering builds manually and on different branches
* Add notice of image name change
> Improved image names & README Improvements (#29)

- .github/workflows/build.yml
This adds proper tags to the images and also adds one for artifacthub so the images show up there.
> chore: add image metadata

- .github/workflows/build.yml
Point to the nvidia readme instead of the base one, fixes #41
> fix: update readme-url

- Containerfile
- README.md
- files/etc/sway/environment
- ublue-os-nvidia-addons.spec
Some configuration file changes have to be made to ensure the Sway session can launch properly with Nvidia.
> feat: Improve sway session compatibility in Sericea image

- Containerfile
Now that there's an [upstream main image](https://github.com/ublue-os/main), we can start to remove unnecessary invocations from the container build manifest and leave only Nvidia-specific functionality.
> feat: switch to upstream main image

- .github/workflows/build.yml
- build.Containerfile
- install.Containerfile
- install.sh
With how many variants being built these days, some caching should be used to reduce build times.
> feat: Break up build process into separate jobs to improve caching in matrix strategy

- README.md
So far the gnashing of teeth has been pretty minimal.
> docs: reword warning on usage

- README.md
> docs: add moz_enable_wayland flag

- justfile
Added the env var ``MOZ_ENABLE_WAYLAND=1`` to the justfile mirroring the change in docs at https://github.com/ublue-os/nvidia/pull/91
> chore: add moz_enable_wayland in justfile

- .github/workflows/build.yml
This simplifies the action and matches the rest of the org
> chore(ci): enable merge queue

- README.md
fixes https://github.com/ublue-os/website/issues/191 (at least I hope so)
> docs: fix nvidia "Verification" section

- post-install.sh
Match the behaviour of: https://github.com/ublue-os/main
> fix: Don't disable rpmfusion after installation

- .github/workflows/build.yml
Wait for https://github.com/ublue-os/main/pull/361 to merge
> chore: re-enable f39

- .github/workflows/build.yml
Move build schedule back for official images
> chore(ci): Build at 3:30 PM UTC

- .github/workflows/build.yml
Fixes: https://github.com/ublue-os/main/issues/464
> fix: remove lxqt 39 as lazurite replaced it

- .github/workflows/build.yml
Relates: https://github.com/ublue-os/main/issues/489
> chore(ci): remove space maximizer

- .github/workflows/build.yml
> chore(ci): fix merging with failed jobs

- .github/workflows/build.yml
This matches retry logic which was added to main repo and a few other places.
> chore(ci): add retry functionality to a few steps

- .github/workflows/reusable-build.yml
I missed this change which is in `main` and `akmods
> refactor: add version specific check to nvidia

- .github/workflows/reusable-build.yml
Urgent fix for bad tagging due to use of outdated variable for nvidia version.
> chore: fix bad version tag for nvidia

- asus/packages.json
> feat(asus): add supergfctl

- .github/workflows/build-39.yml
- .github/workflows/build-40.yml
https://github.com/ublue-os/main/pull/589
> fix: adjust build schedule based on adjustments to main 

- nvidia-install.sh
Add extra option to use /var/tmp as the tmp storage dir
> fix(nvidia): Enable persistenced service

- nvidia-install.sh
Fixes build issues from past few days related to nvidia.
I did test this build locally to confirm it builds cleanly. So we should just need to verify the checks and let it merge.
> fix: change nvidia package names to match negativo17 updates

- Containerfile
- nvidia-install.sh
This wasn't causing a functional problem but it did cause potential confusion.
Fixes: #284
> fix: nvidia kernel.conf reflects reality

- .github/workflows/reusable-build.yml
Do not merge until F41 is released.
> feat: Update Tags for F41 Release
