.github/workflows/build.yml
Containerfile

This change will bring support for building with kinoite-based image to complement silverblue.

Add Kinoite base image support

---

.github/workflows/build.yml
.github/workflows/conventional-commits.yml
.github/workflows/release-please.yml
Containerfile
README.md

Disabling repos can often reduce times that would be spent downloading repo metadata, and can make the build a bit more resilient in the instance of a mirror being down.

Disable unnecessary repos at the end of builds

---

.github/workflows/build.yml
Containerfile
README.md

I added all of the images @ https://quay.io/organization/fedora-ostree-desktops except for beta and buildroot.
Docs rebasing section also reformatted to be the same way as other code blocks. 
Fedora 38 builds are added, so when it releases only docs have to be changed. F37 is still marked as "stable" and "latest", so that nobody unintentionally rebases to F38.
Also: Conventional commits!

Add tons more images, misc docs updates.

---

.github/workflows/build.yml

There's an increasing demand for supporting multiple versions of Fedora and Nvidia drivers simultaneously, and the tagging scheme wasn't set up to handle this well. These changes should enable us to build multiple release streams.

feat: Refactor tagging to support multiple image and driver channels

---

.github/workflows/build.yml

Tag generation logic should be improved further in this change.

Tagging hotfix

---

.github/workflows/build.yml

Fixes the image listings all showing as nvidia and "Vanilla SilverBlue with Nvidia Drivers"

fix: use full image title and updated description for labels

---

Containerfile
README.md

This change introduces more runtime support packages as part of https://github.com/ublue-os/nvidia/issues/35
Credit goes to: https://github.com/ublue-os/bazzite/blob/16b33c1047a049d24143c48359101067297e91b1/Containerfile#L48

feat: Add vaapi packages to enable hardware-accelerated playback

---

Containerfile

This PR fixes a problem I noticed when I switched my "custom kmod image" to be based on this nvidia image rather than the stock silverblue image.
akmods fail to build with message `Unable to open temp file: Permission denied"` if the `FROM` image is one of these ublue-os nvidia images.
The original silverblue image includes `/var/tmp` with normal sticky bit perms, while this image removes `/var`  as part of build cleanup.
The lack of `/var/tmp` causes rpmbuilds (eg, akmod builds) to fail on any container builds which use `ublue-os/nvidia` images as their base because the akmod build will create /var/tmp using the default umask (0022). `/var/tmp` then lacks proper permissions, and akmods fail to create a tmp dir for builds, since `/var/tmp` gets created by root, but `akmods` builds run as …

fix: preserve /var/tmp for akmods builds

---

.github/workflows/build.yml
README.md

This change introduces Nvidia 470xx series support for older Kepler GPUs from 2012-2014.

feat: Add Nvidia 470xx support

---

Containerfile

This change adds the steam-devices package which adds some udev rules for using Steam hardware. This package will be unneeded in the future when the rules are upstreamed:
https://github.com/systemd/systemd/issues/22681

feat: Add steam-devices package

---

.github/workflows/build.yml

Delaying the build by an hour to give `main` images a chance to complete before starting which allows nvidia builds to get the current main updates.

fix: add cron delay to build

---

.github/workflows/build.yml

We don't want builds kicking off when all we do is edit the text files.

chore: have builders ignore text file changes

---

.github/workflows/build.yml
README.md

The nvidia 520xx series is currently broken on Linux 6.2.x kernels, which prevents new builds from being published. This change disables building for that series for now.

fix: disable 520xx series due to broken compatibility in latest kernels

---

.github/workflows/build.yml

See ublue-os/main#88 for more details

fix: maintain oci image version from upstream

---

.github/workflows/build.yml

Works in main, propagating here. 
Co-authored-by: xnasero@posteo.net

chore(ci): refactor: avoid subshell, sign image with env. var

---

.github/workflows/build.yml

First attempt to copy "avoid subshell, sign image with env. var" to this repo was incomplete as this workflow has two distinct build jobs and the second one was missed.
This commit finishes the job, plus prevents the following steps from running in a PR, again, to match the main repo:
- login to GHCR
- push to GHCR
- sign image
- echo push outputs

chore(ci): finish sign refactor and limit pr build

---

.github/workflows/build.yml

It causes checks to never finish when PRing the readme so let's just build everything, yolo.

chore(ci): remove path-ignore

---

.github/workflows/build.yml

This just starts building nvidia sooner after main than we had previously configured as we chose to move akmods before main, not after.
This PR closes #72

chore(ci): build nvidia 1 hour after main

---

generate-akmods-key

This is required for NixOS, where `/usr/bin` contains nothing but `env`. The `sh` shebang does not need to be changed, since `sh` is still in `/bin` on NixOS (in fact, it's the ONLY thing in that directory).

fix: Change bash shebang to use env

---

build.Containerfile
install.Containerfile
install.sh
packages.json
ublue-os-nvidia-addons.spec

The supergfxctl plasmoid allows users to adjust supergfxctl settings directly from the Plasma panel
Resolves: https://github.com/ublue-os/nvidia/issues/99

feat: Add supergfxctl-plasmoid

---

README.md

As mentioned in [https://github.com/elFarto/nvidia-vaapi-driver](https://github.com/elFarto/nvidia-vaapi-driver), setting `widget.dmabuf.force-enabled` to `true` is required on 500+ drivers.

docs: add widget.dmabuf.force-enabled flag

---

.github/workflows/build.yml
README.md

- remove v530 from f38 (fails due to kernel 6.4)
- enable v470 on f38 (wasn't built previously)
- now f38 and f37 are both building v535 and v470
- update README to reflect current state (was out of date)

fix: drop failing v530 driver build

---

.github/workflows/build.yml

I had previously fixed the akmods nvidia build matrix but not the os image variant matrix.

fix: don't attempt to build os images for v530

---

README.md

fix: add signed image prep instructions

---

build.Containerfile
install.sh
ublue-os-nvidia-addons.spec

Since the asus-linux repo we had been using has dropped Fedora 37 support, this introduces a copr repo with support included.

fix: Restore Fedora 37 supergfxctl support

---

install.sh

Adds the supergfxctl-gex extension to Silverblue images for managing multi-GPU Nvidia systems

feat(Silverblue): Add supergfxctl-gex GNOME Shell extension

---

.github/workflows/build.yml
Containerfile
README.md
install.sh

Builds `*-nvidia` images from the nvidia repo instead of main repo.
Adds things which had been added in main repo during the interim period.
- gts tagging
- vesion F39 (commented out temporarily)
- onyx variant
- single rpmfusion mirror for CI builds

chore: revive nvidia builds

---

Containerfile
image-info.sh

Provides a useful reference for the state of the current installed image that can be utilized via ublue update for auto-signing or in scripts to determine what changes to make and exclude
Also ships jq for parsing generated image information
For example...
`jq '."image-flavor"' /usr/share/ublue-os/image-info.json`
... would print the flavor of the image (I.E. nvidia)

feat: Generate image info

---

.github/workflows/build.yml
Containerfile

This was missed when https://github.com/ublue-os/akmods/pull/71 was completed.
Also, shortened workflow job name for easier reading in github UI

fix: use new akmods-nvidia:main-RELEASE tag structure

---

post-install.sh

We added this service to generate nvidia device definitions for container toolkit, but it isn't enabling by default like it should.
This corrects that.

feat: enable ublue-nvctk-cdi.service by default

---

.github/workflows/build.yml

Main images complete and are published in under 20 minutes consistently allowing Nvidia to build closer to when main finishes

chore(ci): Build at 7:30 AM UTC

---

install.sh

Ah while back, I made a change to akmods/main/nvidia repos to force them to use the same rpmfusion mirror during builds (this gets reset to defaults for resulting images).
This is problematic for F39, since, at the least, it will require a path change due to F39 promoting from "development" to "release".
Only merge after https://github.com/ublue-os/main/pull/413 is resolved.

chore: restore default rpmfusion mirror behavior

---

.github/workflows/build.yml

Planned removal of Fedora 37 due to EOL.

feat: Fedora 37 is EOL 2023-12-05

---

install.sh

This consistently pins the build to the same mirror so jobs running on different runners should have the same set of packages to consistently succeed/fail.
This can't succeed until we get a solid build after the merge of https://github.com/ublue-os/main/pull/463

chore(ci): pin to single berkley mirror

---

.github/workflows/build.yml

Validate the integrity of base image being built from via cosign before continuing to build. Ensures we only build from signed images

feat(ci): Verify base image with cosign before building

---

post-install.sh

This symlink was part of an old workaround but breaks ability of downstreams to layer binutils, gcc, etc.
Fixes: #188

fix: remove dangling `ld` symlink

---

install.sh

Switcheroo can do this same task, so we can move supergfxctl to the image-specific change list. Downstream can pass another value to IMAGE_NAME to prevent any part of supergfxctl from being installed.
Could also move this to a separate true/false flag, though that may be less clean.

feat: Make supergfxctl optional based on IMAGE_NAME

---

.github/workflows/build-38.yml
.github/workflows/build-39.yml
.github/workflows/reusable-build.yml
README.md

This will allow us to see if a specific version of Fedora is building or not, plus allow rebuilding only a specific version.
Extra bonus: this will let us adjust merge checks to require success of a subset of versions, eg
"Check all 38 builds successful" and "Check all 39 builds successful" but not 40.
This matches the same style of PR which were merged today in akmods and main.
Closes: https://github.com/ublue-os/main/issues/526

chore(ci): split build workflows by fedora version

---

.github/workflows/reusable-build.yml

Just a cleanup since this build is failing and won't be resolved due to rpmfusion dropping nvidia 470.

chore(ci): nvidia 470 no longer builds for asus 39

---

.github/workflows/reusable-build.yml

Due to the combination of Fedora F38/F39 upgrading to kernel 6.8 and rpmfusion dropping support for nvidia 470 which does not compile on 6.8, we have to drop our nvidia 470 images.

feat: drop support for nvidia 470

---

.github/workflows/reusable-build.yml
Containerfile
nvidia-install.sh

This reworks all the bits in akmods for nvidia:
- removes nvidia driver version as only latest is supported
- uses negativo17 nvidia driver and packages

feat: swap to negativo17 as nvidia driver source

---

.github/workflows/reusable-build.yml
Containerfile
nvidia-install.sh

This reverts the two PRs which were made to support the swap to negativo17 nvidia driver.
This reverts commits:
- 6c4a80abcaf340ccd55f87a0794404dcacdd3395
- ed301734d4c60d8cc1d15f7335af7505386eb93f
I found that this akmods+hwe change was disabling Wayland.
Needs more testing before merging again.

Revert "feat: swap to negativo17 as nvidia driver source"

---

Containerfile
build-initramfs.sh

feat: build initramfs for surface, asus and nvidia

---

surface/packages.json

Fix for #257 
Adding Libraries needed for Camera support on most Surfaces  https://github.com/linux-surface/linux-surface/wiki/Camera-Support#libcamera-support
tested on a Surface Go 8GB  (IR Camera needed to be disabled in BIOS)

fix(surface): Camera support

---

Containerfile

We have been experiencing multiple freezes with the newly released Nvidia 560 drivers, so we will pin to 555 while we investigate.
Depending on what Bazzite chooses to do, we may decide to unpin when they confirm everything is working well.

fix(nvidia): pin Nvidia drivers to 555

---

Containerfile

akmods now properly builds the proprietary driver. Users are also seeing mixed packages so this must go.

Revert "fix(nvidia): pin Nvidia drivers to 555 (#273)"

---

nvidia-install.sh

Upon closer inspection our akmod image already fprovides the KERNEL_MODULE_TYPE variable so no need to compute it.
Relates: #286

refactor: simpler nvidia kernel.conf fix

---

.github/workflows/build-41.yml
.github/workflows/reusable-build.yml

Surface images are the only ones excluded since there are no F41 kernels yet

feat(ci): enable Fedora 41 builds

---

nvidia-install.sh

fix: chromium browser use of hw accel on hybrid laptops
This has been tested via live-stream with multiple ublue-os team members.
We concur that this will retain the fix of pre-loaded nvidia which enables plymouth boot screen to show rather than only a blank screen.
This will, however, pre-load i915 & amdgpu drivers on all nvidia machines, even desktops which only have discrete nvidia cards. It's a fair compromise for us suckers who run nvidia, to have an image which works for all. A loaded kmod which doesn't have any actual hardware though, does not cause harm, just a bit of extra memory used.
The group deemed it a fair trade off for now.
Fixes: #285
fix: use default nvidia driver power management
This fixes power management on optimus laptops, specifically for Ampere+
where the …

fix: nvidia fixes

---

nvidia-install.sh

TL;DR this removes code which is duplicating effort of the upstream defaults.
Longer version:
We submitted a bugfix to upstream negativo17's nvidia driver config to fix power management on optimus laptops. https://github.com/negativo17/nvidia-kmod-common/pull/15
In response @scaronni incorporated another of our changes, setting `NVreg_TemporaryFilePath=/var/tmp`, and suggested some changes for us.
Upstream already specifies nvidia-modprobe and nvidia-persistenced, so they need not be specifically called out in our package install. Also nvidia-persistenced service is already default enabled.

refactor: use upstream nvidia defaults

---

README.md

The build badges are still for Fedora 39 and 40. This PR bumps them to 40 and 41.

chore: update build badges in README

---

install.sh

Removes the deleted asus-linux/firmware git repo, all of these are upstramed
Closes #310

fix: Remove unneeded asus-linux firmware repo

---

nvidia-install.sh

This should ensure that all our nvidia builds (including HWE, Aurora, Bazzite, Bluefin) use the negativo17-nvidia repo which is what we use to build the nvidia-kmod, even if those builds also use negativo17-multimedia.

fix(ci): ensure use of negativo17-nvidia repo (not multimedia)

---

.github/workflows/build-42.yml
.github/workflows/reusable-build.yml

Adds a build for Fedora 42. I'm not super familiar with the tag lifecycle, but I think I've got them correct. 42 is `latest` and `beta`, 41 is `stable` and 40 is `gts`.

Add builds for Fedora 42
